cask_args appdir: "/Applications"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "heroku/brew"

cask "google-chrome"
cask "box-drive"
cask "emacs"
cask "visual-studio-code"
cask "microsoft-office"
cask "microsoft-teams"
cask "zoom"
cask "alfred"
cask "typora"
cask "postman"

cask "font-jetbrains-mono"
cask "choosy"

cask "docker"
brew "docker"

brew "asdf"
brew "tmux"
brew "jq"
brew "jump"
brew "pure"
brew "mas"
brew "fzf"
brew "tree"
brew "bat"
brew "gpg"
brew "zplug"
brew "heroku"
brew "mysql-connector-c"

mas "CyberDuck", id: 409222199
