#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#--------------------------------------------------------
# zplug
#--------------------------------------------------------
export ZPLUG_HOME=/opt/homebrew/opt/zplug
source $ZPLUG_HOME/init.zsh
zplug "plugins/web-search", from:oh-my-zsh
zplug "plugins/history", from:oh-my-zsh
zplug "junegunn/fzf", from:gh-r, as:command, rename-to:fzf
zplug load

#--------------------------------------------------------
# prezto
#--------------------------------------------------------
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
  autoload -U promptinit; promptinit
  prompt pure
fi

# Customize to your needs...
#--------------------------------------------------------
# asdf(arm64) / anyenv(x86_64)
#--------------------------------------------------------
[ `uname -m` = 'arm64' ] && . /opt/homebrew/opt/asdf/libexec/asdf.sh
[ `uname -m` = 'x86_64' ] && eval "$(anyenv init -)"

#--------------------------------------------------------
# jump
#--------------------------------------------------------
eval "$(jump shell)"

#--------------------------------------------------------
# alias
#--------------------------------------------------------
alias emacs="emacs -nw"
alias la="ls -aFG"
alias ls="ls -FG"
alias ll="ls -alFG"
alias dc="docker-compose"
alias do="docker"
alias brewx="arch -x86_64 /usr/local/bin/brew"

#--------------------------------------------------------
# path
#--------------------------------------------------------
# see zprofile.
export PATH="/opt/homebrew/opt/llvm@12/bin:$PATH"

#--------------------------------------------------------
# functions
#--------------------------------------------------------
function md (){
  open -a Typora $1
}

function docker-tags {
  curl -s https://registry.hub.docker.com/v1/repositories/$1/tags | jq -r '.[].name'
}

incremental_search_history() {
  selected=`history -E 1 | fzf | cut -b 26-`
  BUFFER=`[ ${#selected} -gt 0 ] && echo $selected || echo $BUFFER`
  CURSOR=${#BUFFER}
  zle redisplay
}
zle -N incremental_search_history
bindkey "^R" incremental_search_history
[ -f "/Users/kuzukawa/.ghcup/env" ] && source "/Users/kuzukawa/.ghcup/env" # ghcup-env

